feat/test
justincase-jp/blea pull request #24
Opened 2022-02-21 10:50 UTC by defmementomori

## TL;DR
下記のテストを追加
- org-config-rules
- org-config-securityhub
- org-slack

## チケット / Slack のリンク
https://justincase.myjetbrains.com/youtrack/issue/SRE-1257

## 作成・更新・削除される AWS 等のリソース
なし

## Merge 前後で必要な作業（もしあれば）

## レビュー箇所

テスト粒度が適切か悩んだため、もしあればご意見いただきたいです。

## エビデンス(構築したリソースが動いているところのスクリーンショットなど)

テストが通ることを確認

```
jest /Users/kota.tomimatsu/work/development/JustInCase/blea/test/*
 PASS  test/org-events.test.ts (25.634 s)
 PASS  test/org-slack.test.ts (26.544 s)
 PASS  test/org-config-rules.test.ts (26.752 s)
 PASS  test/org-config-securityhub.test.ts
----------------------------------|---------|----------|---------|---------|-------------------
File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------------------|---------|----------|---------|---------|-------------------
All files                         |   79.59 |       75 |      60 |   79.38 |                   
 src                              |   80.25 |       75 |   71.43 |   80.25 |                   
  index.ts                        |     100 |      100 |     100 |     100 |                   
  org-account-init.ts             |   31.58 |      100 |       0 |   31.58 | 33-108            
  org-config-rules.ts             |     100 |       75 |     100 |     100 | 31                
  org-config-securityhub.ts       |     100 |       75 |     100 |     100 | 45-50             
  org-events.ts                   |     100 |      100 |     100 |     100 |                   
  org-slack.ts                    |     100 |      100 |     100 |     100 |                   
  org-stackset.ts                 |      50 |      100 |       0 |      50 | 20-23             
 src/lambda                       |      60 |      100 |       0 |      60 |                   
  disable-securityhub-function.ts |      60 |      100 |       0 |      60 | 17-24             
  sw-role-function.ts             |      60 |      100 |       0 |      60 | 17-24             
 src/resources                    |     100 |      100 |     100 |     100 |                   
  chatbot-role.ts                 |     100 |      100 |     100 |     100 |                   
----------------------------------|---------|----------|---------|---------|-------------------

Test Suites: 4 passed, 4 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        31.181 s
```

2022-02-22 02:53 UTC, YutaOkoshi commented on .editorconfig
> +quote_type = single
ちょうど困っていました
ありがとうございます👍

2022-02-22 02:59 UTC, YutaOkoshi commented on test/org-config-securityhub.test.ts
> +});
ここらへんについては `cdk-constants` での指定は難しそうでしょうか。。。？
AWS側でPolicy名の変更がたまにあるので`cdk-constants`で指定しておけば変更が必要なときは楽だなと思いました🙇‍♂️

2022-02-28 00:52 UTC, defmementomori commented on test/org-config-securityhub.test.ts
> +});
了解です、修正しました

2022-02-28 04:38 UTC, YutaOkoshi requested changes
CIがエラーになってしまっているみたいなのでご確認をお願いします！🙏

https://github.com/justincase-jp/blea/runs/5353497554?check_suite_focus=true
https://github.com/justincase-jp/blea/runs/5353513342?check_suite_focus=true

2022-03-05 01:32 UTC, YutaOkoshi approved these changes

2022-03-05 01:32 UTC, merged